### PR TITLE
Remove user_id attribute from analysis table create dto

### PR DESCRIPTION
**Pull request by raffomania**
Here's a proposal for fixing #322.

It results in slightly more code, but the API would be a lot cleaner. I'm not sure if we can make this a little more concise in the backend still.

### CODE REVIEW

**Review by bigabig — COMMENTED** [review]
Ich finde das ganz gut so. Ich frag mich, ob man irgendwie darum herum kommen kann, ein extra InternalCreate DTO zu erstellen.

@floschne hast du da Ideen?

**Comment by floschne** [comment]
Yes, I also like it! Especially, because now we have the `authz` user in every call, which makes the IDs redundant. 

I might oversee something here but, couldn't we just make the ID in the create DTOs optional? That is, the client (UI) does not provide it but it gets auto-injected into the create_dto in the backend. It might even work with a FastAPI dependency that we could add to the routes?

**Comment by raffomania** [comment]
I've tried your suggestion, and it works. However, it's tricky to verify that endpoints actually do set the user_id field, and if an endpoint doesn't do that, we'd actually save *unverified* user id values sent from the client instead :/

**Comment by floschne** [comment]
Hmm, I see. Can we force to override the `authz` `user_id` if a `user_id` is set from the client?

**Comment by raffomania** [comment]
After a quick session with Tim, we found a solution to make an optional field kind of work:

- With a field validator, we can always set the user_id to `None` when it's coming in from the client
- Using a custom schema configuration, we can hide the field from the openapi spec

However, this comes with a few disadvantages:

- Using a typehint of `user_id: Optional[int]` causes type errors in many places where the user_id field is accessed in the backend
- Using a typehint of `user_id: int` fixes the type errors, but obfuscates the fact that it's *sometimes* `None`
- When constructing DTOs in the backend, we now have to skip validation to prevent the `user_id` field being set to `None`, resulting in quite some refactoring

All in all, the previous solution using two separate DTOs seems easier to understand and cleaner to me, at the cost of a little verbosity. I've talked to Tim about this and we agreed to let you decide which route we should take :D

**Comment by raffomania** [comment]
@floschne I'll assign this to you since I'm stopping work on DATS for now :)

**Pull request closed without merging**
